version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: senmeann/zero2prod
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@newsletter:5432" # Database connection string
    ports:
      - "8000:8000"
    depends_on:
      - db # Ensure db service starts before api service
  db:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
    db:
      driver: local